name: Gestueworks
markdown: redcarpet

# Don't include README or Gemfile in compiled site
exclude: [README.md, Gemfile, Gemfile.lock]

assets:
  cache: true
  cachebust: soft

  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _vendor/javascripts
    - _vendor/stylesheets
    - _vendor/images
